[package]
name = "luminance-glyph"
version = "0.1.0"
authors = ["John Doneth <doneth7@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["font", "ttf", "truetype", "luminance", "text"]
readme = "README.md"
repository = "https://github.com/JohnDoneth/luminance_glyph"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luminance = "0.39"
luminance-derive = "0.5"
glyph_brush = "0.7"
log = "0.4.8"

[dev-dependencies]
luminance-derive = "0.5"
luminance-glfw = "0.12"
luminance-glutin = "0.9"